# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.db import migrations, models
import django.db.models.deletion
import hostel.service.variables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('vlanid', models.AutoField(db_column='vlanID', primary_key=True, serialize=False)),
                ('vlannum', models.IntegerField(unique=True, validators=[hostel.service.variables.validate_vlan_id])),
                ('vname', models.CharField(max_length=20, unique=True, validators=[hostel.service.variables.validate_vlan_name])),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket', models.CharField(max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=2048, null=True)),
                ('multivlan', models.BooleanField(default=False)),
                ('is_management', models.BooleanField(default=False)),
                ('is_local', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan', to='common.Service')),
            ],
            options={
                'db_table': 'vlans',
                'managed': True,
            },
        ),
    ]
