# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vlans', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('clients', '0002_auto_20201017_2132'),
        ('common', '0002_auto_20201017_2132'),
        ('devices', '0002_auto_20201017_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='devices.Device'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='remote_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_bundles', to='devices.Device'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='vlans',
            field=models.ManyToManyField(related_name='bundles', through='common.BundleVlan', to='vlans.Vlan'),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='archivedservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_services', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='subservice',
            unique_together={('sub_id', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('bundle', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bundlevlan',
            unique_together={('bundle', 'vlan')},
        ),
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('device', 'name')},
        ),
    ]
