# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.db import migrations, models
import django.db.models.deletion
import hostel.service.variables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vlans', '0001_initial'),
        ('devices', '0001_initial'),
        ('common', '0002_auto_20201017_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(db_column='ipaddress', default='')),
                ('ipaddress_from', models.BigIntegerField()),
                ('ipaddress_to', models.BigIntegerField()),
                ('netmask', models.IntegerField(default=32, validators=[hostel.service.variables.validate_netmask])),
                ('description', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, choices=[('+', '+'), ('-', '—')], default='+', max_length=20)),
                ('mac', models.CharField(blank=True, max_length=17, null=True, validators=[hostel.service.variables.validate_mac])),
                ('comment', models.CharField(blank=True, max_length=2048)),
                ('ptr', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.CharField(max_length=20, null=True)),
                ('protected', models.BooleanField(default=False)),
                ('is_allocation', models.BooleanField(default=False)),
                ('allocated_for', models.CharField(blank=True, choices=[('', ''), ('service', 'Выдан клиенту под услугу'), ('internal', 'Управление/наши ресурсы'), ('info', 'Простой аллокейшн, информационный'), ('service_range', 'Диапазон выдачи под услугу')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allocating_service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_net', to='common.Ourservice')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nets', to='common.City')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net', to='devices.Device')),
                ('management_vlan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_net', to='vlans.Vlan')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net', to='common.Service')),
                ('subservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nets', to='common.SubService')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nets', to='vlans.Vlan')),
            ],
            options={
                'db_table': 'nets',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='net',
            unique_together={('ipaddress_from', 'ipaddress_to')},
        ),
    ]
