# Generated by Django 2.0.5 on 2021-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net',
            name='ticket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
