# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('router', 'Маршрутизатор'), ('switch', 'Коммутатор'), ('server', 'Сервер'), ('transponder', 'Транспондер'), ('kvm', 'Виртуалка'), ('ups', 'Бесперебойник'), ('nas', 'NAS'), ('pdu', 'Управляемая розетка'), ('t8', 'T8'), ('mux', 'Мультиплексор'), ('phone', 'Телефон'), ('other', 'Непонятное')], max_length=20, null=True)),
                ('model', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, choices=[('juniper', 'Juniper Networks'), ('extreme', 'Extreme Networks'), ('cisco', 'Cisco Systems'), ('edjecore', 'Edgecore Networks'), ('huawei', 'Huawei'), ('ubiquity', 'Ubiquiti Networks'), ('t8', 'T8'), ('dlink', 'D-link'), ('lofis', 'Lofis'), ('mikrotik', 'Mikrotik'), ('opticin', 'Opticin'), ('other', 'Другое')], max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=2048, null=True)),
                ('serial', models.CharField(default='', max_length=255)),
                ('unit_height', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store',
                'managed': True,
            },
        ),
    ]
