# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(default='', max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('partner_type', models.CharField(choices=[('client', 'Клиент'), ('provider', 'Поставщик')], default='client', max_length=15)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('is_terminated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='clients.Client')),
                ('company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='companies.Company')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('application_type', models.CharField(choices=[('order', '1. Заказ'), ('akt', '2. Акт к заказу/приложению'), ('application', '3. Приложение'), ('other', '0. Другое')], default='other', max_length=25)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applications', to='docs.Agreement')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docs',
                'managed': True,
            },
        ),
    ]
