# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.db import migrations, models
import django.db.models.deletion
import hostel.service.variables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20201017_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('netname', models.CharField(max_length=255, unique=True, validators=[hostel.service.variables.validate_netname])),
                ('start_unit', models.IntegerField(null=True)),
                ('rack_placement', models.CharField(choices=[('front', 'С передней стороны стойки'), ('back', 'С задней стороны стойки')], default='front', max_length=20)),
                ('whole_rack_depth', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('router', 'Маршрутизатор'), ('switch', 'Коммутатор'), ('server', 'Сервер'), ('transponder', 'Транспондер'), ('kvm', 'Виртуалка'), ('ups', 'Бесперебойник'), ('nas', 'NAS'), ('pdu', 'Управляемая розетка'), ('t8', 'T8'), ('mux', 'Мультиплексор'), ('phone', 'Телефон'), ('other', 'Непонятное')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('+', '+'), ('-', '—')], default='+', max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=2048, null=True)),
                ('community', models.CharField(blank=True, max_length=40, null=True)),
                ('version', models.CharField(blank=True, max_length=512, null=True)),
                ('is_managed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('datacenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='common.Datacenter')),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
    ]
