# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('common', '0002_auto_20201017_2132'),
        ('nets', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='management_net',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_device', to='nets.Net'),
        ),
        migrations.AddField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Rack'),
        ),
        migrations.AddField(
            model_name='device',
            name='store_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='store.Entry'),
        ),
    ]
