# Generated by Django 2.0.5 on 2021-10-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_photos'),
        ('devices', '0002_auto_20201017_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='photos',
            field=models.ManyToManyField(to='common.Photo'),
        ),
    ]
