# Generated by Django 2.1.5 on 2020-10-17 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'CREATE'), ('change', 'CHANGE'), ('delete', 'DELETE')], max_length=25)),
                ('object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.IntegerField(null=True)),
                ('object_str', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spy_log',
                'managed': True,
            },
        ),
    ]
